### ISSUE TITLE
open/close

### ISSUE THREAD

**Issue by shamb0t** [orbitdb/orbit-db-keystore#23]
Keystore currently opens/closes level store with each interaction with storage to avoid level error `LOCK:already held by process`.  This could be avoided by either changing the path used for the keystore or returning the same keystore if the path is already opened

**Comment by BartKnucle** [comment]
Hi! Do you have an implementation example with default configuration?

**Comment by BartKnucle** [comment]
@shamb0t nevermid, @aphelionz fix the issue 👍 💃

**Comment by thiagodelgado111** [comment]
I believe this is related:
![image](https://user-images.githubusercontent.com/1891013/57730821-ad276b80-766f-11e9-8a06-c9c40e9a7ff4.png)

**Comment by aphelionz** [comment]
Absolutely. If you want to experiment check out the `fix/#persistent-leveldb-connection` branch of this repo.

**Comment by thiagodelgado111** [comment]
@aphelionz awesome! Loved the adapter idea :)

**Comment by aphelionz** [comment]
Thank you! Let me know if you have any other feedback

**Comment by aphelionz** [comment]
Closing for now, we can track elsewhere
