### ISSUE TITLE
"hasKey" raises unhandled promise rejection

### ISSUE THREAD

**Issue by thiagodelgado111** [orbitdb/orbit-db-keystore#27]
This is a problem that happened to me on test environment (ava). It fails the test because of a unhandled promise rejection. Maybe there's a better way to, well, handle it? 😄 

![image](https://user-images.githubusercontent.com/1891013/57411115-03556400-71c3-11e9-8aeb-d63e14ce088d.png)

paging @shamb0t

**Comment by shamb0t** [comment]
Thanks for reporting @thiagodelgado111! This should be fixed by https://github.com/orbitdb/orbit-db-keystore/pull/28
